[opener]
edit = [
  { run = 'nvim %s', block = true, for = "windows", desc = "nvim" },
]

[open]
prepend_rules = [
  { mime = "text/*", use = "edit" },
  { url = "*.toml", use = "edit" },
  { url = "*.json", use = "edit" },
  { url = "*.lua", use = "edit" },
  { url = "*.cpp", use = "edit" },
  { url = "*.hpp", use = "edit" },
  { url = "*.h", use = "edit" },
  { url = "*.c", use = "edit" },
  { url = "*.py", use = "edit" },
  { url = "*.ts", use = "edit" },
  { url = "*.tsx", use = "edit" },
  { url = "*.cmake", use = "edit" },
]
